### ISSUE TITLE
NVDA and CC images are not a link

### ISSUE THREAD

**Issue by dstorey** [dstorey/HTML5accessibility#14]
Not sure how to do this without wrapping entire thing in an anchor or duplicating (bad)

**Comment by dstorey** [comment]
@melanierichards might need some design advice on this one (somewhat related to link styles in Creative Commons in footer).

I could technically put the image in via CSS probably and keep it the way it is, but it feels like making the ad in CSS rather than part of the markup is weird (no ads are delivered that way).

I could wrap the whole thing as a link (rather than just donate text), which is what I guess most ads are, but that'd make all the text the blue/green highlight colour.  

We could perhaps get away with not giving any special link colour and rely on the fact it looks like an ad unit to make people click on it. Or perhaps have a lighter weight link affordance for that unit, like just an underline or something (perhaps too busy still)

We could have two links (one for ad, and one for the donate text) but that is bad a11y, which would be ironic for an ad for a screen reader.

**Comment by melanierichards** [comment]
@dstorey what if we removed the comma after "Donate to NVDA", capitalized "The", and wrapped the link element around the ad and "Donate to NVDA"? Would that text feel awkwardly-written?

**Comment by dstorey** [comment]
@melanierichards then you'd need two <P>. Something like:

``` HTML
<a>
    <img/>
    <p>Donate to NVDA</p>
</a>
<p>bla bla bla</p>
```

Which will probably break up the reading in screen readers and make it semantically two different paragraphs. Especially when reading in paragraph mode (I guess). Feels hacky either way.

**Comment by melanierichards** [comment]
Well then:

a) wrap the `a` around all of it and use `span`s to fake regular text.
b) 2 links. But bad for the reasons you mentioned.
