### ISSUE TITLE
Implement Redlines phase 2: font sizes

### ISSUE THREAD

**Issue by dstorey** [dstorey/HTML5accessibility#16]

**Comment by dstorey** [comment]
Depends on #4

**Comment by melanierichards** [comment]
Body copy: 18px/24px Work Sans Regular (#555)

## Header area
- Page title: 48px/1 League Spartan Bold (#333)
- Page subtitle: 21px/28px Work Sans Regular (#555)
- Nav items: (#333)

## Browser cards
- % title: 54px/1 Work Sans Extra Light (#333; wonder if we could subset only the chars we need: 1-9 and %)
- Browser name: 14px/20px Work Sans Semi Bold (#555)
- OS name: same, but Regular weight

## About area
- Main large text: 28px/40px Work Sans Light (#555)
- NVDA callout: 13px/24px League Sans Bold (#333)

## Element support
- Section titles ("Feature Support", for ex): 20px/24px League Spartan Bold (#333)
- Category titles: Same, just uppercase
- "Key": 13px/1 League Spartan Bold (#333)
- Key labels: body copy
- Table headers: 13px/1 League Spartan Bold (#333), uppercase
- Feature name: 21px/28px Work Sans Regular (link color)
- "Accessibly supported": 16px/24px Work Sans Semibold (#555)
- Child criteria: same, but Regular weight

## How to test content
- Most of this is body copy. Small titles: 13px/1 League Spartan Bold (#333), uppercase

## Notes content
- Same as above.
- Creative Commons callout: same as NVDA
- Button: 13px/1 League Spartan Bold (#fff), uppercase

**Comment by dstorey** [comment]
Closing this as I think it is ± correct now. Open bugs for things that are different. Header comes to mind (especially on mobile needs correct sizes)
