### ISSUE TITLE
Implement Redlines phase 3: colours

### ISSUE THREAD

**Issue by dstorey** [dstorey/HTML5accessibility#17]

**Comment by dstorey** [comment]
Depends on #4

**Comment by melanierichards** [comment]
Some font colors are in issue #16.

Link color: #2b7a82
Link styles, hover: #f16529, border-bottom is #f16529 and 2px. If this causes a shift we can fake the underline w/ an absolutely positioned pseudo element or come up with something else.
Link styles, active: No underline? Any suggestions?

Nav link styles, hover: #f16529, border-bottom is #f16529 and 2px. If this causes a shift we can fake the underline w/ an absolutely positioned pseudo element or come up with something else.

Browser green bars: #99a83e
"Amber" bars: #cc983a
Red bars: #c14d35

Github button bg / CC icons: #333
Github button bg, hover / CC icons, hover: #f16529 (text color #000 or is that too halloweeny?)
"", active: 50% opacity.

Text selection: white bg, black text. Or if that doesn't feel accessible enough, #333 bg, white text.

**Comment by dstorey** [comment]
text selection is almost invisible: 
![screen shot 2016-03-10 at 1 14 44 am](https://cloud.githubusercontent.com/assets/465069/13664640/4eec0878-e65d-11e5-8b05-b3c2016edd74.png)

**Comment by dstorey** [comment]
I think i've set everything to spec. Differences:
- I've kept the 50% opacity underline for links from test page. Spec above doesn't include colour, but the mockups do have a underline. I like that it is a slightly different color.
- I've not included the orange/black github hover as it looks like a new brand of Hershey’s chocolate ;)
- wasn't sure if the active state was suppose to be opacity: .5 or just hsla/rgba for the bg at .5
- no active state for links yet.
- used option 2 for text selection as 1 doesn't show up (screen shot above)
- not changed icons on hover as would require second icon I don't have right now. Consider when/if we used SVG sprites where it should be fairly easy. Not sure the CC icon needs to change colour as it is far enough away from CC text, but the github icon will if we swap text from white to black

Comments/questions:
- need colours for the two different colour of borders in the table (header thick border looks different colour to tbody borders)
- still need colour for CC text I think, as it is a link, but on mocks it isn't styled as one. Which direction do we go? Left as generic link for now.
- I'm not sure I'm sold on the orange hover colours. Probably a personal preference but I don't like orange and green together. Feels college sports team or something. I like the 2px underline though as looks less fragile than 1px can against descenders. Would keeping the 2px but changing out the colour while keeping the text colour or using a darker shade / lighter tint of the link colour work?

**Comment by dstorey** [comment]
Also we need to look at hover underline of nav links. I currently make anchors the width of the text, but for hit target reasons they should probably be full width (to end of dotted lines below). Does it look too stripy (either now or with latter behaviour)?

Also need focus colour/style

**Comment by melanierichards** [comment]
@dstorey

> need colours for the two different colour of borders in the table (header thick border looks different colour to tbody borders)

All table border colors are #a2a2a2 (I think the header thick border thing is just an illusion; that border is 4px thick). The only except is the parent row of an expanded feature, which has #000 borders (child criteria rows are still #a2a2a2).

> still need colour for CC text I think, as it is a link, but on mocks it isn't styled as one. Which direction do we go? Left as generic link for now.

Woops, I misremembered this as just the CC icons being linked, but in the live site it's both. So just style the link text as the link is styled in the NVDA callout.

> I'm not sure I'm sold on the orange hover colours. Probably a personal preference but I don't like orange and green together. Feels college sports team or something. I like the 2px underline though as looks less fragile than 1px can against descenders. Would keeping the 2px but changing out the colour while keeping the text colour or using a darker shade / lighter tint of the link colour work?

Sure, I think I like making it a darker shade better. Maybe #1e565c? (Taken from here: http://www.0to255.com/2b7a82)

> Also we need to look at hover underline of nav links. I currently make anchors the width of the text, but for hit target reasons they should probably be full width (to end of dotted lines below). Does it look too stripy (either now or with latter behaviour)?

If we make the anchors full-width, the underline should probably be on a span that contains just the width of the text.

> Also need focus colour/style

I kinda just like the Edge default: 1px dotted #000 outline. Thoughts?

**Comment by dstorey** [comment]
Closing this.
