### ISSUE TITLE
Add key

### ISSUE THREAD

**Issue by dstorey** [dstorey/HTML5accessibility#19]

**Comment by dstorey** [comment]
@melanierichards I made the margin between the title above and key 10 px smaller, as a) it looked too big (again) compared to red lines (almost 50% between title and title below) and the red line shows it lining up to top of key: label, while using 32px margin is 32 between bottom of line height of title above and the padding box of the key, which has a bunch of extra pixels as it is inline with the key items, which are taller due to the bigger font size. It looked around 10px difference using the screenshot tool measure thingy.

**Comment by dstorey** [comment]
Not sure what the margin is between bottom of key and the section and grouping title. it is currently the default 40px given for the titles and the tables above, but it looks way smaller than in the mockup, so I suspect it needs extra.

Also with the key icons being bg images, i couldn't give 8px between the icon and the label. Instead I gave 28px (avg width of icon) and added 3 extra to yes as it is wider than the other icons.

**Comment by melanierichards** [comment]
@dstorey margin between bottom of key and the section and grouping title: 64px. Sorry for missing that one :(

The thing about 8px b/t icon and label sounds fine. Anything else you still need on here?

**Comment by dstorey** [comment]
Think it is working now. Key horizontal margins are different to mockup but doesn't look out of place.
