### ISSUE TITLE
Try alt strategy for adding dotted lines to cells

### ISSUE THREAD

**Issue by dstorey** [dstorey/HTML5accessibility#22]
Currently use bg image, but it is overloaded with the bg for the status icon.

This requires duplication for each icon, which isn't super terrible, but I need to change the colour when the row is expanded, and that will mean changing it for each status type too, which is crazy. 

Hopefully it will work with border-image like in the header.

**Comment by dstorey** [comment]
Not working out how to get a gradient in border image to repeat its middle part as there is no equivalent of background-size. it is stretching the bottom transparent part, instead of just repeating the middle dotted part.

**Comment by dstorey** [comment]
@melanierichards can you make me an SVG file:

Straight vertical line, the width of the dotted lines for the vertical table borders (2px wide?)

Top and bottom 8px transparent (or however big the empty space above/below is)

Middle of the line a black square and below that a transparent square (2px each?)…in reality, that would be 8px trans, 2px black, 10px trans.

The top and bottom 8px would be used for the top and bottom left corner of the border image. the 4px in the middle is the middle slice, that with the repeat keyword will get repeated to fill the rest of the height of the cell. (as only doing a left border, don't need the pixels for repeating the top / bottom / right border and the top/bottom right corners)

I tried doing this with a gradient but there is no way to set background-size for the gradient in border-image, so it was stretching the gradient and I couldn't get the repeated slice part.

**Comment by dstorey** [comment]
Width and height of the svg file should be width="2px" height="20" (if the 2px and 8px sizes are correct)

**Comment by melanierichards** [comment]
@dstorey hopefully this is what you were looking for, come grab me if not.

[dotted-line.zip](https://github.com/dstorey/HTML5accessibility/files/188360/dotted-line.zip)

**Comment by dstorey** [comment]
@melanierichards  ![lddga8r](https://cloud.githubusercontent.com/assets/465069/14035268/83b9c6d4-f1e9-11e5-8060-05136dd4fc78.gif)
