### ISSUE TITLE
New site icon, and font-sizes for main page header on mobile (and tablet)

### ISSUE THREAD

**Issue by dstorey** [dstorey/HTML5accessibility#30]
Mobile currently has guesstimate for page title at present.

Also needs other text sizes in header checked. I believe nav links are correct but subtitle might need updating

**Comment by dstorey** [comment]
@melanierichards also need favicon.

**Comment by melanierichards** [comment]
Mobile logo:

[html5-a11y-logo-mobile.svg.zip](https://github.com/dstorey/HTML5accessibility/files/188240/html5-a11y-logo-mobile.svg.zip)

@dstorey Can you give me specs for the favicon? Do you want a 16px icon or some fancier set?
