### ISSUE TITLE
Make hover state consistent between test cases and main page

### ISSUE THREAD

**Issue by dstorey** [dstorey/HTML5accessibility#33]
Main page :hover:
# 1e565c

bottom border: 2px

Test case:
#333

bottom border, default 1px of non-hover state.

@melanierichards can you take a look at both and choose which one you prefer. I think I like the 2px more, but don't have strong opinion on colour.

**Comment by melanierichards** [comment]
#1e565c with 2px, shmaybe? Unless the #333 seems more noticeable to you and therefore more accessible? Funny how I forgot I already gave the test pages a hover state...

**Comment by melanierichards** [comment]
I put in a PR on AT-browser-tests, will close this issue if/when that gets merged.

**Comment by melanierichards** [comment]
Steve merged this, closing.
