### ISSUE TITLE
Redlines

### ISSUE THREAD

**Issue by dstorey** [dstorey/HTML5accessibility#4]
Measurements so far have been taken by eye by comparing to designs, and trying to keep to x4 for the most part. 

Need official redline values or guidance on which are wrong and need updating. Max-width of body is biggest difference at the moment, and the text colour.

**Comment by melanierichards** [comment]
@dstorey

[HTML5 A11y Redlines.pdf](https://github.com/dstorey/HTML5accessibility/files/166018/HTML5.A11y.Redlines.pdf)

^ Contains redlines for margins and padding.

Notes:
- Font style redlines will come in next.
- In the child table rows, the vertical padding is actually more like 16px but let's try 12px and see how that looks.

**Comment by dstorey** [comment]
Closing this and handling separately.
