### ISSUE TITLE
script on output test fails

### ISSUE THREAD

**Issue by cyns** [dstorey/HTML5accessibility#59]
<form oninput="result.value=parseInt(a.value)+parseInt(b.value)">
                    <input name="b" type="range" value="50"> +
                    <input name="a" type="number" value="10"> =
                    <output id="output1" name="result"></output>
                </form>

SCRIPT5009: 'result' is undefined
output.html (36,20)

**Comment by dstorey** [comment]
@cyns I believe this is https://github.com/ThePacielloGroup/AT-browser-tests/pull/51 which Steve hasn't merged yet.
